name: hello-world
on:
  pull_request:
    types: [ labeled ]
jobs:
  tests:
    if: ${{ github.event.label.name == 'run' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: my-step 2
        run: ./gitrise.sh --access-token $BITRISE_TOKEN --slug $BITRISE_APP_SLUG --workflow script --branch $GITHUB_REF