name: hello-world
on:
  pull_request:
    types: [ labeled ]
jobs:
  tests:
    if: ${{ github.event.label.name == 'run' }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step 1
        run: ls ../..
      - name: my-step 2
        run: ./gitrise.sh -a $BITRISE_TOKEN -s $BITRISE_APP_SLUG -w script -b $GITHUB_REF